name: Documentation and Guides

# Run every time a new commit pushed to main or for pull requests
on:
  push:
    branches:
      - main

  pull_request:

env:
  SIMULATION: native

jobs:

  build-docs:
    name: cFE Documentation
    runs-on: ubuntu-18.04

    steps:
      - name: Install Dependencies
        run: sudo apt-get install doxygen graphviz -y

        # Check out the cfs bundle
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      # Prepare build "recipes"
      - name: Copy Files
        run: |
          cp ./cfe/cmake/Makefile.sample Makefile
          cp -r ./cfe/cmake/sample_defs sample_defs

      # Setup the build system
      - name: Make Prep
        run: make prep

      - name: Build Docs
        run: |
          make doc > make_doc_stdout.txt 2> make_doc_stderr.txt

      # Upload documentation logs as artifacts
      - name: Archive Documentation Build Logs
        uses: actions/upload-artifact@v2
        with:
          name: cFS Docs Artifacts
          path: |
            make_doc_stdout.txt
            make_doc_stderr.txt

      - name: Error Check
        run: |
          if [[ -s make_doc_stderr.txt ]]; then
            cat make_doc_stderr.txt
            exit -1
          fi

  build-usersguide:
    # Name the Job
    name: Users Guide
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false

      # Setup the build system
      - name: Copy Files
        run: |
          cp ./cfe/cmake/Makefile.sample Makefile
          cp -r ./cfe/cmake/sample_defs sample_defs

      # Setup the build system
      - name: Make Prep
        run: make prep

      - name: Install Dependencies
        run: sudo apt-get install doxygen graphviz -y

      - name: Build Usersguide
        run: |
          make usersguide > make_usersguide_stdout.txt 2> make_usersguide_stderr.txt
          mv build/doc/warnings.log usersguide_warnings.log

      - name: Archive Users Guide Build Logs
        uses: actions/upload-artifact@v2
        with:
          name: Users Guide Artifacts
          path: |
            make_usersguide_stdout.txt
            make_usersguide_stderr.txt
            usersguide_warnings.log


      - name: Error Check
        run: |
          if [[ -s make_usersguide_stderr.txt ]]; then
            cat make_usersguide_stderr.txt
            exit -1
          fi

      - name: Warning Check
        run: |
          if [[ -s usersguide_warnings.log ]]; then
            cat usersguide_warnings.log
            exit -1
          fi

      - name: PDF generation installs
        if: ${{ github.event_name == 'push' }}
        run: |
          sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: PDF generation
        if: ${{ github.event_name == 'push' }}
        run: |
          set -x
          mkdir deploy
          cd ./build/doc/users_guide/latex
          make > build.txt
          mv refman.pdf $GITHUB_WORKSPACE/deploy/cFE_Users_Guide.pdf
          # Could add pandoc and convert to github markdown
          # pandoc CFE_Users_Guide.pdf -t gfm

      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy
          CLEAN: false
          SINGLE_COMMIT: true

  build-osalguide:
    # Name the Job
    name: Osal Guide
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false

      # Setup the build system
      - name: Copy Files
        run: |
          cp ./cfe/cmake/Makefile.sample Makefile
          cp -r ./cfe/cmake/sample_defs sample_defs

      # Setup the build system
      - name: Make Prep
        run: make prep

      - name: Install Dependencies
        run: sudo apt-get install doxygen graphviz -y

      - name: Build OSAL Guide
        run: |
          make osalguide > make_osalguide_stdout.txt 2> make_osalguide_stderr.txt
          mv build/doc/warnings.log osalguide_warnings.log


      - name: Archive Osal Guide Build Logs
        uses: actions/upload-artifact@v2
        with:
          name: OSAL Guide Artifacts
          path: |
            make_osalguide_stdout.txt
            make_osalguide_stderr.txt
            osalguide_warnings.log


      - name: Error Check
        run: |
          if [[ -s make_osalguide_stderr.txt ]]; then
            cat make_osalguide_stderr.txt
            exit -1
          fi

      - name: Warning Check
        run: |
          if [[ -s osalguide_warnings.log ]]; then
            cat osalguide_warnings.log
            exit -1
          fi

      - name: PDF generation installs
        if: ${{ github.event_name == 'push' }}
        run: |
          sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: PDF generation
        if: ${{ github.event_name == 'push' }}
        run: |
          mkdir deploy
          cd ./build/doc/osalguide/latex
          make > build.txt
          mv refman.pdf $GITHUB_WORKSPACE/deploy/OSAL_Users_Guide.pdf
          # Could add pandoc and convert to github markdown
          # pandoc CFE_Users_Guide.pdf -t gfm

      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy
          CLEAN: false
          SINGLE_COMMIT: true

