name: Changelog

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Force bash to apply pipefail option so pipeline failures aren't masked
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issuesLabel: "### Closed issues"
          breakingLabel: "### Breaking changes"
          enhancementLabel: "### Implemented enhancements"
          bugsLabel: "### Fixed bugs"
          deprecatedLabel: "### Deprecated"
          removedLabel: "### Removed"
          securityLabel: "### Security fixes"
          pullRequests: false
          author: false

      - name: "Upload changelog"
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "Changelog"
          path: CHANGELOG.md
